### ISSUE TITLE
Magos

### ISSUE THREAD

**Issue by Nahuel-N** [pdep-utn-frd/presentacion-2021-nadiamata#2]
Por curiosidad cual es tu personaje favorito o que te guste de la saga? escena que te guste de la peli?

te dejo, los mios:

Personaje: Bellatrix Lestrange. 

Escena: Una puede ser Hermione borrando la memoria de los padres.

https://www.youtube.com/watch?v=-H0JParMivs&ab_channel=WizardingWorld

**Comment by nadiamata** [comment]
Magos preferidos: 
-Hermione (por su fidelidad además de inteligencia)
-Severus Snape (A pesar de las decisiones que tomó en su vida pudo redimirse. Demuestra que todos nos equivocamos y podemos tener una segunda oportunidad)

Escena: 
1) La de Harry y Hermione bailando . Porque Hermione siempre lo cuidaba a Harry pero en ese momento él se dio cuenta que tenia que cuidarla a ella.
2) Hermione golpeando a Malfoy
